Added redis container

diff --git a/bin/craft b/bin/craft
--- a/bin/craft
+++ b/bin/craft
@@ -1,6 +1,7 @@
 #! /usr/bin/env bash
 
 MYSQL_CONTAINER="mysql:5.6"
+REDIS_CONTAINER="redis:5.0"
 CRAFT_CONTAINER="codemonauts/craft-cms-dev-env"
 
 function should_pull {
@@ -22,13 +23,21 @@ case "$1" in
 
   'start')
     mkdir -p ${HOME}/databases
+    mkdir -p ${HOME}/redis
     mkdir -p ${HOME}/database_config
     if should_pull "$MYSQL_CONTAINER"; then
       echo "Pulling new MySQL container..."
       docker pull "$MYSQL_CONTAINER" > /dev/null
     fi
+    if should_pull "$REDIS_CONTAINER"; then
+      echo "Pulling new REDIS container..."
+      docker pull "$REDIS_CONTAINER" > /dev/null
+    fi
     docker run --rm -d --name mysql -p 3306:3306 -v "${HOME}/databases:/var/lib/mysql" -v "${HOME}/database_config:/etc/mysql/conf.d" -e MYSQL_ROOT_PASSWORD=root "$MYSQL_CONTAINER"
-    if [ $? == 0 ]; then
+    mysql=$?
+    docker run --rm -d --name redis -v "${HOME}/redis:/data" "$REDIS_CONTAINER"
+    redis=$?
+    if [ "$mysql" == 0 ] && [ "$redis" == 0 ]; then
       if should_pull "$CRAFT_CONTAINER"; then
         echo "Pulling new craft container..."
         docker pull "$CRAFT_CONTAINER" > /dev/null
@@ -37,14 +46,14 @@ case "$1" in
       if [ -z $PHPVERSION ]; then
         PHPVERSION="7.0"
       fi 
-      docker run --rm -d --name craft -p 8080:80 -v "${PWD}:/local" -e "PHPVERSION=$PHPVERSION" --link mysql:mysql "$CRAFT_CONTAINER"
+      docker run --rm -d --name craft -p 8080:80 -v "${PWD}:/local" -e "PHPVERSION=$PHPVERSION" --link mysql:mysql --link redis:redis "$CRAFT_CONTAINER"
       if [ $? == 0 ]; then
         echo "Started Craft CMS environment in ${PWD} and databases stored to ${HOME}/databases."
       else
         echo "Error starting webserver container. See error messages above!"
       fi
     else
-      echo "Error starting MySQL container. See error messages above!"
+      echo "Error starting MySQL or Redis container. See error messages above!"
     fi
     ;;
 
